name: VanillaPlus
version: ${version}
main: dev.ezpadaz.vanillaPlus.VanillaPlus
api-version: '26.1.2'

author: Molthor226
description: Modular vanilla-plus SMP utilities for Paper 26.1.2

softdepend: [AuraSkills]
